//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria_MS_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Admin
    {
        [Required(ErrorMessage = "This field is Required to Continue")]
        public int id { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        public string name { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        public string username { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        [DataType(DataType.PhoneNumber)]
        public string contact { get; set; }
    }
}
