//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria_MS_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.PizzaOrders = new HashSet<PizzaOrder>();
        }

        [Required(ErrorMessage = "This field is Required to Continue")]
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "This field is Required to Continue")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is Required to Continue")]
        public string Address { get; set; }

        [Required(ErrorMessage = "This field is Required to Continue")]
        [DataType(DataType.PhoneNumber)]
        public string Contactno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PizzaOrder> PizzaOrders { get; set; }
    }
}
