//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria_MS_webAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PizzaOrder
    {

        [Required(ErrorMessage = "This field is Required to Continue")]
        public int OrderID { get; set; }

        public Nullable<int> CustomerID { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        public string PizzaName { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> UnitPrice { get; set; }
        [Required(ErrorMessage = "This field is Required to Continue")]
        public Nullable<int> Qty { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
